import { test, expect } from '@playwright/test'

test.skip(!process.env.E2E_DATABASE_URL, '完整路径需要独立测试数据库')

test('新用户建档、完成第一课并复习', async ({ page }) => {
  expect((await page.request.get('/api/today')).status()).toBe(401)
  const email = `learner-${crypto.randomUUID()}@example.test`
  await page.goto('/register')
  await page.getByLabel('昵称').fill('测试学习者')
  await page.getByLabel('邮箱').fill(email)
  await page.getByLabel('密码', { exact: true }).fill('TestPassword123!')
  await page.getByLabel('确认密码').fill('TestPassword123!')
  await page.getByRole('button', { name: '创建账户' }).click()
  await expect(page.getByText('你最想用日语做什么？')).toBeVisible()
  await page.getByRole('button', { name: '下一步' }).click()
  await page.getByRole('button', { name: '下一步' }).click()
  await page.getByRole('button', { name: '开始第一课' }).click()
  await expect(page).toHaveURL(/\/today$/)
  await page.getByRole('link', { name: /继续学习/ }).click()
  await expect(page).toHaveURL(/\/learn\//)
  await page.getByRole('button', { name: '开始学习' }).click()
  await page.getByRole('button', { name: '去练习' }).click()

  const cards = page.locator('article.card')
  await expect(cards).toHaveCount(5)
  await cards.nth(0).getByRole('button', { name: 'a', exact: true }).click()
  const firstRequest = page.waitForRequest((request) => request.url().endsWith('/api/attempts') && request.method() === 'POST')
  await cards.nth(0).getByRole('button', { name: '检查答案' }).click()
  const firstPayload = (await firstRequest).postDataJSON()
  await expect(cards.nth(0).getByText('回答正确。继续保持主动回忆。')).toBeVisible()
  const duplicate = await page.request.post('/api/attempts', { data: firstPayload })
  expect(duplicate.ok()).toBe(true)
  expect((await duplicate.json()).duplicate).toBe(true)
  await cards.nth(1).getByRole('textbox', { name: '你的答案' }).fill('i')
  const feedbackResponse = page.waitForResponse((response) => response.url().endsWith('/api/ai/feedback'))
  await cards.nth(1).getByRole('button', { name: '检查答案' }).click()
  expect((await feedbackResponse).status()).toBe(200)
  await expect(cards.nth(1).getByRole('status')).toBeVisible()

  const canvas = cards.nth(2).getByLabel('描摹 あ')
  await canvas.scrollIntoViewIfNeeded()
  const box = await canvas.boundingBox()
  expect(box).not.toBeNull()
  await page.mouse.move(box!.x + 50, box!.y + 50)
  await page.mouse.down()
  await page.mouse.move(box!.x + 100, box!.y + 100)
  await page.mouse.up()
  await cards.nth(2).getByRole('button', { name: '记录描摹' }).click()
  await cards.nth(3).getByRole('button', { name: '爱', exact: true }).click()
  await cards.nth(3).getByRole('button', { name: '检查答案' }).click()
  await cards.nth(4).getByRole('button', { name: '上面', exact: true }).click()
  await cards.nth(4).getByRole('button', { name: '检查答案' }).click()
  await page.getByRole('button', { name: '主动回忆' }).click()
  await page.getByRole('button', { name: '完成回忆' }).click()
  await expect(page.getByText('课程完成', { exact: true })).toBeVisible()
  await page.getByRole('link', { name: '回到今日计划' }).click()
  await expect(page.getByText('1/1 完成')).toBeVisible()

  await page.goto('/review')
  await page.getByRole('link', { name: '开始复习' }).click()
  await page.getByRole('button', { name: '显示答案' }).click()
  await page.getByRole('button', { name: /Good/ }).click()
  await expect(page.getByRole('heading', { name: '本轮复习完成' })).toBeVisible()
  await page.goto('/companion')
  await expect(page.getByText('完成课程')).toBeVisible()
  await expect(page.getByText('完成复习')).toBeVisible()
  await expect(page.getByText('22/100 经验')).toBeVisible()
  await expect(page.getByText('今天状态：为你庆祝')).toBeVisible()

  if (test.info().project.name === 'mobile') await expect(page.getByRole('navigation', { name: '移动导航' }).getByRole('link', { name: '设置' })).toBeVisible()
  await page.goto('/settings')
  await page.getByLabel('主题', { exact: true }).selectOption('dark')
  await page.getByLabel('字体大小').selectOption('large')
  await page.getByLabel('显示假名辅助').uncheck()
  await page.getByLabel('听力播放').uncheck()
  await page.getByRole('button', { name: '保存设置' }).click()
  await expect(page.getByText('已保存')).toBeVisible()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
  await expect(page.locator('html')).toHaveAttribute('data-font-scale', 'large')
  await page.reload()
  await expect(page.getByLabel('字体大小')).toHaveValue('large')
  await expect(page.getByLabel('听力播放')).not.toBeChecked()
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
})

test('有基础用户完成独立摸底而不产生复习卡', async ({ page }) => {
  const email = `placement-${crypto.randomUUID()}@example.test`
  await page.goto('/register')
  await page.getByLabel('昵称').fill('摸底学习者')
  await page.getByLabel('邮箱').fill(email)
  await page.getByLabel('密码', { exact: true }).fill('TestPassword123!')
  await page.getByLabel('确认密码').fill('TestPassword123!')
  await page.getByRole('button', { name: '创建账户' }).click()
  await expect(page.getByText('你最想用日语做什么？')).toBeVisible()
  await page.getByRole('button', { name: '下一步' }).click()
  await page.getByRole('button', { name: '下一步' }).click()
  await page.getByRole('button', { name: /先做 5 分钟摸底/ }).click()
  await page.getByRole('button', { name: '开始第一课' }).click()
  await expect(page).toHaveURL(/\/practice\/placement$/)
  for (const [index, answer] of ['a', 'kya', 'は', 'か', 'それ'].entries()) {
    await expect(page.getByText(`${index + 1}/5`)).toBeVisible()
    await page.getByRole('button', { name: answer, exact: true }).click()
    await page.getByRole('button', { name: '检查答案' }).click()
    await page.getByRole('button', { name: '下一题' }).click()
  }
  await expect(page.getByRole('heading', { name: '摸底完成' })).toBeVisible()
  await expect(page.getByText(/5 题中答对 5 题/)).toBeVisible()
  await page.goto('/review')
  await expect(page.getByText('没有到期卡片')).toBeVisible()
})
